# Generated by Django 4.2 on 2023-04-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("HD", "후드티"),
                            ("JN", "청바지"),
                            ("SO", "양말"),
                            ("HT", "모자"),
                        ],
                        default="type",
                        max_length=2,
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        choices=[
                            ("HD001", "hood-001"),
                            ("HD002", "hood-002"),
                            ("HD003", "hood-003"),
                            ("JN001", "jean-001"),
                            ("SO001", "socks-001"),
                            ("HT001", "hat-001"),
                        ],
                        default="N/A",
                        max_length=5,
                    ),
                ),
                (
                    "product_size",
                    models.CharField(
                        choices=[
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("F", "Free"),
                        ],
                        default="N/A",
                        max_length=1,
                    ),
                ),
                ("product_name", models.CharField(max_length=15)),
                ("product_price", models.CharField(max_length=10)),
                ("product_desc", models.TextField()),
                ("product_quantity", models.IntegerField(default=0)),
            ],
            options={"db_table": "my_product",},
        ),
        migrations.CreateModel(
            name="Inbound",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="erp.product",
                    ),
                ),
                ("inbound_quantity", models.IntegerField(default=0)),
                ("inbound_date", models.DateTimeField(auto_now_add=True)),
            ],
            bases=("erp.product",),
        ),
        migrations.CreateModel(
            name="Outbound",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="erp.product",
                    ),
                ),
                ("outbound_quantity", models.IntegerField(default=0)),
                ("outbound_date", models.DateTimeField(auto_now_add=True)),
            ],
            bases=("erp.product",),
        ),
    ]
